mode: sixmax
blinds:
  sb: 50
  bb: 100
stacks_bb: 100
seeds: [501]
seat_replicas: 6
hands_per_replica: 50
lineup:
  - baseline:glm-6
  - baseline:gpt5-6
  - baseline:gemini-6
  - baseline:deepseek-6
  - baseline:kimi-6
  - baseline:doubao-6
population_mirroring: true
