mode: sixmax
blinds:
  sb: 50
  bb: 100
stacks_bb: 100
seeds: [501]
seat_replicas: 6
hands_per_replica: 50
lineup:
  - baseline:gpt5-6?model=gpt-5&name=GPT5-Pro
  - baseline:gpt5-6?model=gpt-5-mini&name=GPT5-Mini
  - baseline:gemini-6
  - baseline:deepseek-6
  - baseline:kimi-6
  - baseline:gpt5-6?model=gpt-5-nano&name=GPT5-nano
population_mirroring: true
