mode: hu
blinds:
  sb: 50
  bb: 100
stacks_bb: 100
seeds: [601]
hands_per_seed: 100
replicas: 2
lineup:
  - baseline:deepseek-hu?system_prompt=Please play as conservatively as possible.&name=DeepSeek-Conservative
  - baseline:deepseek-hu
